// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAH4ogvnQ4INNTw_tlicYUotmY_wlCpFzU',
    appId: '1:137975535295:web:4dbc5b95d68785fda6d80a',
    messagingSenderId: '137975535295',
    projectId: 'olaz-test',
    authDomain: 'olaz-test.firebaseapp.com',
    storageBucket: 'olaz-test.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBc35pRe8XCynBArPZDG2ucvy5qRDaYmec',
    appId: '1:137975535295:android:b8af56f149d676bca6d80a',
    messagingSenderId: '137975535295',
    projectId: 'olaz-test',
    storageBucket: 'olaz-test.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAo1lOZH6WQrygWzcLIpMIF-HTOYvzPEgY',
    appId: '1:137975535295:ios:2b91f536da380d6ba6d80a',
    messagingSenderId: '137975535295',
    projectId: 'olaz-test',
    storageBucket: 'olaz-test.appspot.com',
    iosClientId: '137975535295-p14ela4scf8om2b67s9hsjvkkhd8o3fr.apps.googleusercontent.com',
    iosBundleId: 'com.example.olaz',
  );
}
